import type { ToolDefinition } from '@toolorbit/tool-registry';

export const devTools: ToolDefinition[] = [
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    category: 'developer',
    kind: 'client-pure',
    icon: 'braces',
    description: 'Format, validate, and beautify JSON with instant error highlighting.',
    component: 'JsonFormatter',
    seo: {
      title: 'JSON Formatter & Validator — Free Online Tool',
      description:
        'Format and validate JSON instantly in your browser. Catch syntax errors with line-level detail and beautify with custom indentation. No upload.',
      keywords: ['json formatter', 'json validator', 'beautify json', 'json pretty print', 'json lint'],
      faq: [
        {
          q: 'Does this tool send my JSON anywhere?',
          a: 'No. Parsing and formatting both happen with the built-in JSON.parse and JSON.stringify functions in your browser. Your data never leaves your device.',
        },
        {
          q: 'What happens if my JSON has a syntax error?',
          a: 'The tool catches the parse error and shows you the message JavaScript itself produces, so you can jump straight to the problem instead of scanning the whole document by eye.',
        },
        {
          q: 'Can I change the indentation width?',
          a: 'Yes, the formatter supports 2-space, 4-space, and tab indentation so the output matches your project\u2019s style guide.',
        },
      ],
      content: `
        <p>JSON is the format almost every API, config file, and log line speaks, but raw JSON
        that arrives minified, copy-pasted from a terminal, or generated by another program is
        often unreadable. A formatter takes that flat string and rebuilds it with consistent
        indentation, line breaks, and spacing so the structure of the data — which keys are
        nested under which objects, where arrays start and end — is visible at a glance.</p>
        <p>This formatter does two things at once: it validates, and it beautifies. Validation
        means it actually parses your input using the same JSON engine your browser uses
        everywhere else, so if there's a trailing comma, an unescaped quote, or a missing
        bracket, you get a real parser error rather than a guess. Beautification means once the
        parse succeeds, the tool re-serializes the data with your chosen indentation so it reads
        cleanly whether you're debugging an API response, reviewing a configuration file, or
        preparing a payload to paste into documentation.</p>
        <p>Because the entire process runs with native browser JavaScript — no server round trip
        — formatting is instant even on large documents, and nothing about the content of your
        JSON is logged, stored, or transmitted anywhere. That matters if you're working with
        API responses that include tokens, internal config, or anything else you wouldn't want
        passing through a third-party server. Paste, format, copy the result, and the tab can be
        closed without a trace.</p>
        <p>Common uses include cleaning up a minified API response before reading it, checking
        whether a hand-written config file is syntactically valid before deploying it, comparing
        two JSON payloads more easily once both are consistently formatted, and turning a single
        long line of JSON pulled from logs into something a teammate can actually review in a
        pull request.</p>
      `.trim(),
    },
    related: ['json-minifier', 'jwt-decoder', 'regex-tester', 'base64-codec'],
  },
  {
    slug: 'json-minifier',
    name: 'JSON Minifier',
    category: 'developer',
    kind: 'client-pure',
    icon: 'minimize-2',
    description: 'Strip whitespace from JSON to produce the smallest valid payload.',
    component: 'JsonMinifier',
    seo: {
      title: 'JSON Minifier — Compress JSON Online Free',
      description:
        'Remove all unnecessary whitespace from JSON to shrink payload size for APIs, config files, or storage. Validates first, so you never minify broken JSON.',
      keywords: ['json minifier', 'compress json', 'minify json online', 'remove json whitespace'],
      faq: [
        {
          q: 'Is minified JSON still valid JSON?',
          a: 'Yes. Whitespace between tokens is not meaningful in JSON, so removing it changes nothing about how the data parses — only how many bytes it takes to transmit or store.',
        },
        {
          q: 'Will this tool minify invalid JSON?',
          a: 'No, the input is parsed first. If it fails to parse, you will see the error instead of a minified (but broken) result, which prevents shipping malformed output.',
        },
      ],
      content: `
        <p>Minifying JSON means removing every character that exists purely for human
        readability — spaces, tabs, and line breaks between tokens — while keeping the data
        itself completely unchanged. A parser never cares whether an object's keys are spread
        across ten lines or crammed onto one; it produces the exact same result either way. The
        only thing that changes is the byte count, which is the entire point of minifying in the
        first place.</p>
        <p>That byte count matters more than it might seem. An API response served to thousands
        of requests per second, a config file bundled into a deploy, or a JSON blob stored in a
        database column all benefit from being as small as possible — smaller payloads transfer
        faster, compress better over gzip or brotli, and take up less space at rest. Shaving even
        15-20% off a large JSON document by removing formatting whitespace is a free win with
        zero risk to correctness, as long as the minification step itself doesn't introduce
        errors.</p>
        <p>This tool minimizes that risk by parsing your input as real JSON before producing any
        output. If the input doesn't parse — a stray comma, a missing quote — you'll see the
        error immediately rather than silently shipping a minified file that's also broken. Once
        parsing succeeds, the tool re-serializes the data with zero extra whitespace and gives you
        a one-click copy of the compact result, plus a simple before/after size comparison so you
        can see exactly how many bytes you saved.</p>
        <p>Typical use cases: shrinking a large fixture file before committing it to a repo,
        preparing a JSON payload to embed inline in HTML or a script tag, or compressing
        configuration data before storing it in a size-constrained field like a cookie or a
        database column with strict limits.</p>
      `.trim(),
    },
    related: ['json-formatter', 'base64-codec', 'url-codec'],
  },
  {
    slug: 'base64-codec',
    name: 'Base64 Encode / Decode',
    category: 'developer',
    kind: 'client-pure',
    icon: 'binary',
    description: 'Encode text to Base64 or decode Base64 back to plain text, with full UTF-8 support.',
    component: 'Base64Codec',
    seo: {
      title: 'Base64 Encoder & Decoder — Free Online Tool',
      description:
        'Encode plain text to Base64 or decode Base64 back to readable text, with correct UTF-8 handling for emoji and non-Latin scripts. Runs in your browser.',
      keywords: ['base64 encode', 'base64 decode', 'base64 converter', 'base64 online'],
      faq: [
        {
          q: 'Why does my Base64 output look different from other tools?',
          a: 'Some older Base64 tools only support plain ASCII and mangle anything outside that range, like emoji, Bangla, or accented characters. This tool encodes through UTF-8 first, so non-Latin text round-trips correctly.',
        },
        {
          q: 'Is Base64 encryption?',
          a: 'No. Base64 is an encoding, not encryption — it has no secret key, and anyone can decode it instantly. It is meant for safely representing binary or text data inside formats that only support plain text, not for hiding sensitive information.',
        },
        {
          q: 'Can I encode files, not just text?',
          a: 'This version focuses on text input. File-to-Base64 conversion (for embedding images as data URIs, for example) is on the roadmap as the Image Tools module ships.',
        },
      ],
      content: `
        <p>Base64 is a way of representing arbitrary data using only 64 printable characters —
        the upper and lowercase Latin alphabet, the digits 0-9, and two symbols. It exists
        because many older protocols and formats, like email and certain parts of URLs and JSON,
        were only designed to safely carry plain text, not arbitrary binary bytes. Encoding data
        as Base64 turns it into something those systems can transport without corruption, at the
        cost of roughly 33% more characters than the original.</p>
        <p>Encoding text to Base64 and decoding it back is one of the most common small tasks in
        web development: embedding small images directly in CSS or HTML as data URIs, reading the
        payload section of a JWT (which is itself Base64URL-encoded JSON), passing binary-ish data
        through systems that only accept text fields, or basic obfuscation of values in a config
        file that aren't meant to be secret but shouldn't be plainly readable either.</p>
        <p>A detail that trips up a lot of naive implementations: the built-in browser functions
        btoa and atob only work correctly on text within the Latin-1 character range. Feed them an
        emoji, a Bangla character, or most accented letters and they either throw an error or
        silently produce garbage. This tool routes text through a proper UTF-8 encoding step
        first, so anything you type — any script, any emoji — encodes and decodes correctly,
        round-trip, every time.</p>
        <p>It's worth being clear about what Base64 is not: it is not encryption and provides no
        confidentiality. Decoding a Base64 string requires no key or password, just the decode
        operation itself. If you need to protect sensitive data, Base64 is the wrong tool entirely
        — use it only when the goal is compatibility with text-only systems, not secrecy.</p>
      `.trim(),
    },
    related: ['url-codec', 'jwt-decoder', 'json-formatter', 'hash-generator'],
  },
  {
    slug: 'url-codec',
    name: 'URL Encode / Decode',
    category: 'developer',
    kind: 'client-pure',
    icon: 'link',
    description: 'Percent-encode or decode URLs and query string components.',
    component: 'UrlCodec',
    seo: {
      title: 'URL Encoder & Decoder — Free Online Tool',
      description:
        'Encode special characters for safe use in URLs and query strings, or decode percent-encoded URLs back to text. Component and full-URL modes.',
      keywords: ['url encoder', 'url decoder', 'percent encoding', 'uri encode online'],
      faq: [
        {
          q: 'What\u2019s the difference between the two modes?',
          a: 'Component mode (encodeURIComponent) escapes every character that isn\u2019t safe inside a single query parameter, including & and =. Full-URL mode (encodeURI) leaves those characters alone because they\u2019re structurally meaningful in a complete URL.',
        },
        {
          q: 'Why do spaces turn into %20?',
          a: '%20 is the percent-encoded form of a space character. URLs cannot contain literal spaces, so any tool that builds or transmits a URL replaces them with this escape sequence (or sometimes a + sign in form-encoded data specifically).',
        },
      ],
      content: `
        <p>URLs can only safely contain a limited set of characters — letters, digits, and a
        handful of punctuation marks. Everything else, from spaces to ampersands to non-Latin
        text, has to be represented using percent-encoding: a % followed by the character's hex
        byte value. A space becomes %20, an ampersand inside a value becomes %26, and so on. This
        tool handles that translation in both directions.</p>
        <p>There are two distinct encoding modes because URLs have structure, and not every
        character should be escaped everywhere. Component mode, built on encodeURIComponent,
        treats the input as a single value — a query parameter, a path segment — and escapes
        every character that could otherwise be misread as part of the URL's structure, including
        &, =, and ?. Full-URL mode, built on encodeURI, assumes you're encoding an entire URL and
        deliberately leaves structural characters like /, ?, &, and = untouched, since escaping
        those would break the URL rather than protect it.</p>
        <p>Decoding reverses either process: feed in a percent-encoded string and get back the
        original readable text, useful when you're debugging a URL you copied from a browser's
        address bar, inspecting a redirect target, or reading query parameters that have been
        encoded by a backend framework into something hard to scan visually.</p>
        <p>This comes up constantly when building or debugging anything that constructs URLs
        programmatically: building a share link that includes a title with spaces and
        punctuation, reading a tracking parameter that's been encoded by an ad platform, or
        figuring out exactly what a webhook payload's redirect_uri actually points to before
        trusting it.</p>
      `.trim(),
    },
    related: ['base64-codec', 'json-formatter', 'regex-tester'],
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    category: 'developer',
    kind: 'client-pure',
    icon: 'fingerprint',
    description: 'Generate cryptographically random v4 UUIDs, one at a time or in bulk.',
    component: 'UuidGenerator',
    seo: {
      title: 'UUID Generator — Free Online v4 UUID Tool',
      description:
        'Generate RFC 4122 version 4 UUIDs using your browser cryptographic random number generator. Bulk-generate up to 100 at once, copy as a list.',
      keywords: ['uuid generator', 'guid generator', 'random uuid', 'uuid v4 online'],
      faq: [
        {
          q: 'How random are these UUIDs really?',
          a: 'Generation uses crypto.randomUUID(), a built-in browser API backed by the operating system\u2019s cryptographically secure random number generator — the same quality of randomness used for things like session tokens.',
        },
        {
          q: 'What\u2019s the chance of a collision?',
          a: 'A version 4 UUID has 122 random bits. You would need to generate roughly a billion UUIDs every second for about 85 years before the probability of a single collision reaches 50%, which is why UUIDs are treated as effectively unique in practice.',
        },
        {
          q: 'Can I generate more than one at a time?',
          a: 'Yes, the bulk mode generates up to 100 UUIDs in one click and lets you copy them as a newline-separated list, handy for seeding test data or database fixtures.',
        },
      ],
      content: `
        <p>A UUID — universally unique identifier — is a 128-bit value almost always written as
        32 hex characters split into five groups, like 3fa85f64-5717-4562-b3fc-2c963f66afa6.
        Version 4, the variant this tool generates, fills nearly all of those 128 bits with
        random data, which is what makes UUIDs practical: two systems anywhere in the world,
        with no coordination or central registry between them, can each generate an identifier
        and trust it won't collide with the other's.</p>
        <p>That property is why UUIDs are everywhere in modern software: primary keys in
        databases where you don't want sequential, guessable IDs; request IDs for tracing a
        single operation across distributed logs; session and API key identifiers; and unique
        names for temporary files or resources created by multiple processes at once. Anywhere
        you need an identifier guaranteed not to clash with one generated somewhere else, a v4
        UUID is the standard answer.</p>
        <p>The quality of the randomness matters. This tool uses crypto.randomUUID(), a native
        browser function backed by the operating system's cryptographically secure random number
        generator — not Math.random(), which is fast but not designed to be unpredictable and
        should never be relied on for anything where collision resistance or unpredictability
        actually matters.</p>
        <p>For situations needing more than one — seeding a test database, generating placeholder
        IDs for a mock API response, or preparing fixture data for a migration script — the bulk
        mode generates up to 100 UUIDs in a single click, each one independently random, ready to
        copy as a list.</p>
      `.trim(),
    },
    related: ['password-generator', 'hash-generator', 'json-formatter'],
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    category: 'developer',
    kind: 'client-pure',
    icon: 'key-round',
    description: 'Generate strong, random passwords with configurable length and character sets.',
    component: 'PasswordGenerator',
    seo: {
      title: 'Password Generator — Strong Random Passwords Online',
      description:
        'Generate strong, random passwords with adjustable length and character sets. Includes a real-time strength meter. Generated entirely in your browser.',
      keywords: ['password generator', 'random password', 'strong password generator', 'secure password online'],
      faq: [
        {
          q: 'Are passwords sent anywhere or logged?',
          a: 'No. Every password is generated locally using crypto.getRandomValues(), your browser\u2019s cryptographically secure random number source, and nothing about the result is transmitted or stored.',
        },
        {
          q: 'How is password strength calculated?',
          a: 'The strength meter estimates entropy from length and the size of the character set you\u2019ve enabled, which approximates how many guesses a brute-force attacker would need — it\u2019s an estimate, not a guarantee, since real-world cracking also depends on the attacker\u2019s methods.',
        },
        {
          q: 'Should I reuse a generated password across sites?',
          a: 'No — generate a unique password per account and store them in a password manager. Reusing even a strong password means one breached site can compromise every other account using it.',
        },
      ],
      content: `
        <p>A strong password is, fundamentally, one that's hard to guess and hard to brute-force
        — which in practice means long, random, and drawn from a wide character set, with no
        dictionary words, personal details, or predictable patterns an attacker (or a piece of
        cracking software) could exploit. Humans are reliably bad at generating this kind of
        randomness by hand; we gravitate toward patterns, substitutions, and memorable structures
        that are exactly what password-cracking tools are built to exploit.</p>
        <p>This tool removes the human element from the randomness. Every character is selected
        using crypto.getRandomValues(), the Web Crypto API's cryptographically secure random
        number generator — the same class of randomness used to generate session tokens and
        encryption keys, not the weaker Math.random() that's adequate for games but not security.
        You control the length and which character sets are included — lowercase, uppercase,
        digits, and symbols — and the tool composes a password drawing from exactly those pools.</p>
        <p>A live strength meter estimates entropy based on length and character-set size, giving
        you immediate feedback on whether a given configuration produces something resistant to
        brute-force guessing, or something that's technically random but still too short to be
        meaningfully secure. As a rule of thumb, longer consistently beats more complex: a 20-
        character password using only letters and digits is harder to crack than a 10-character
        one stuffed with every symbol available.</p>
        <p>One important caveat this tool can't solve on its own: generating a strong password is
        only half the job. It needs to be unique per account and stored somewhere safe — a
        password manager, not a sticky note or a reused pattern — because even an unguessable
        password becomes a liability the moment it's reused across multiple accounts and one of
        those accounts gets breached.</p>
      `.trim(),
    },
    related: ['uuid-generator', 'hash-generator'],
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    category: 'developer',
    kind: 'client-pure',
    icon: 'hash',
    description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from text input.',
    component: 'HashGenerator',
    seo: {
      title: 'Hash Generator — MD5, SHA-1, SHA-256, SHA-512 Online',
      description:
        'Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from text instantly using the Web Crypto API. Useful for checksums and integrity checks.',
      keywords: ['hash generator', 'sha256 online', 'md5 generator', 'sha1 hash', 'checksum tool'],
      faq: [
        {
          q: 'Which hash algorithm should I use?',
          a: 'For anything security-relevant, use SHA-256 or SHA-512 — MD5 and SHA-1 are both cryptographically broken and should only be used for non-security purposes, like checking whether two files happen to match.',
        },
        {
          q: 'Can a hash be reversed back to the original text?',
          a: 'No, hashing is one-way by design. There is no operation that turns a hash back into the original input; the only way to "reverse" one is to guess inputs and hash them until you find a match, which is exactly why weak, short, or predictable inputs are still risky to hash.',
        },
        {
          q: 'Why does MD5 produce a shorter output than SHA-256?',
          a: 'Each algorithm produces a fixed-length output regardless of input size — MD5 always outputs 128 bits (32 hex characters), SHA-256 always outputs 256 bits (64 hex characters), and so on. The length is a property of the algorithm, not the input.',
        },
      ],
      content: `
        <p>A hash function takes any input — a single word, a password, an entire file's worth of
        text — and deterministically produces a fixed-length string of characters called a digest.
        The same input always produces the same digest, a tiny change to the input produces a
        completely different digest, and there's no way to work backward from the digest to
        recover the original input. That combination of properties is what makes hashing useful
        for integrity checks, fingerprinting, and (with the right algorithms) password storage.</p>
        <p>This tool supports four algorithms. MD5 and SHA-1 are included because they're still
        widely used in legacy systems and for non-security checksums, like quickly confirming two
        copies of a file are identical — but both have known cryptographic weaknesses
        (collision attacks) and should never be used for anything where security actually matters,
        like hashing passwords. SHA-256 and SHA-512, part of the SHA-2 family, remain
        cryptographically strong and are the standard choice for integrity verification,
        certificate fingerprints, and as a building block in proper password-hashing schemes.</p>
        <p>All computation happens through the Web Crypto API's built-in digest function (for
        SHA-1/256/512) and a lightweight JS implementation for MD5, entirely inside your browser
        — your input text is never transmitted anywhere, which matters if you're hashing
        something sensitive like an API secret you're trying to fingerprint without exposing the
        secret itself.</p>
        <p>Common uses: verifying a downloaded file's checksum matches what the publisher listed,
        generating a content fingerprint to detect whether a document has changed, creating
        cache-busting keys derived from file contents, or producing test fixtures for code that
        needs to validate hash output.</p>
      `.trim(),
    },
    related: ['uuid-generator', 'password-generator', 'base64-codec'],
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    category: 'developer',
    kind: 'client-pure',
    icon: 'regex',
    description: 'Test regular expressions against sample text with live match highlighting.',
    component: 'RegexTester',
    seo: {
      title: 'Regex Tester — Test Regular Expressions Online',
      description:
        'Test JavaScript regular expressions against your own text with live match highlighting, capture groups, and flag toggles. Runs entirely client-side.',
      keywords: ['regex tester', 'regular expression tester', 'regex online', 'test regex javascript'],
      faq: [
        {
          q: 'Which regex flavor does this use?',
          a: 'JavaScript\u2019s native RegExp engine — the same one running in Chrome, Firefox, Safari, and Node.js. Behavior may differ slightly from PCRE, Python\u2019s re module, or other flavors in edge cases like lookbehind support or Unicode handling.',
        },
        {
          q: 'Why isn\u2019t my pattern matching anything?',
          a: 'The most common cause is a missing flag — without the g flag a pattern only reports the first match, and without i it won\u2019t match case-insensitively. Check the flag toggles first.',
        },
        {
          q: 'Can I see capture groups, not just the full match?',
          a: 'Yes, each match is broken down into its full match plus any numbered or named capture groups, so you can confirm exactly what each group of your pattern is extracting.',
        },
      ],
      content: `
        <p>Regular expressions are powerful precisely because they're compact — a single line can
        describe a complex pattern of text — but that same compactness makes them notoriously
        hard to write correctly on the first try and even harder to debug by reading silently. A
        regex tester closes that loop: write a pattern, see immediately which parts of your
        sample text it matches, and iterate until the pattern behaves exactly as intended.</p>
        <p>This tool runs JavaScript's native RegExp engine — the exact same implementation
        powering pattern matching in every Chromium and Firefox browser and in Node.js — so what
        you test here will behave identically wherever you paste the final pattern into a real
        project. Toggle the standard flags (g for global, i for case-insensitive, m for multiline,
        s for dot-matches-newline) and watch matches update live as you type, with every match
        highlighted directly in your sample text.</p>
        <p>Beyond highlighting, each match is broken down into its capture groups — both numbered
        groups like (\\d+) and named groups like (?&lt;year&gt;\\d{4}) — so you can confirm a
        pattern isn't just matching the right text overall but actually extracting the right
        pieces into the right groups, which is usually the part of a regex that's hardest to get
        right and easiest to get subtly wrong.</p>
        <p>Typical use cases: validating an email or phone number format before committing it to
        a form's validation logic, writing a find-and-replace pattern for a bulk text edit,
        extracting structured data like dates or IDs out of unstructured log lines, or simply
        understanding what a regex copied from Stack Overflow or generated by AI actually does
        before dropping it into production code.</p>
      `.trim(),
    },
    related: ['json-formatter', 'url-codec', 'lorem-ipsum-generator'],
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    category: 'developer',
    kind: 'client-pure',
    icon: 'shield-check',
    description: 'Decode JSON Web Tokens to inspect the header, payload, and expiry.',
    component: 'JwtDecoder',
    seo: {
      title: 'JWT Decoder — Inspect JSON Web Tokens Online',
      description:
        'Decode a JWT to view its header, payload, and signature, with automatic expiry checking. Your token never leaves your browser.',
      keywords: ['jwt decoder', 'decode jwt online', 'jwt parser', 'json web token decoder'],
      faq: [
        {
          q: 'Does this tool verify the JWT signature?',
          a: 'No, and intentionally so. Verifying a signature requires the secret or public key, which this tool never asks for. It only decodes the header and payload, which are Base64URL-encoded but not encrypted, so they\u2019re readable without any key in the first place.',
        },
        {
          q: 'Is it safe to paste a real production token here?',
          a: 'Decoding happens entirely client-side and nothing is transmitted, but as a general rule, avoid pasting live session tokens into any third-party tool when you can test with an expired or sample token instead.',
        },
        {
          q: 'How does the expiry check work?',
          a: 'If the payload contains a standard "exp" claim, the tool reads that Unix timestamp and compares it to the current time to tell you whether the token is currently valid or already expired.',
        },
      ],
      content: `
        <p>A JSON Web Token is three Base64URL-encoded segments joined by dots: a header
        describing the signing algorithm, a payload holding the actual claims (user ID, issued-at
        time, expiry, and whatever else the issuer included), and a signature that proves the
        token wasn't tampered with — but only to someone holding the right secret or key. The
        header and payload are not encrypted, just encoded, which means anyone can read them
        without any key at all; the signature is the only part that requires a secret, and only
        to verify, not to read.</p>
        <p>That distinction is exactly what this tool relies on. It decodes the header and payload
        segments back to readable JSON so you can inspect exactly what claims a token carries —
        useful when you're debugging an auth flow and need to confirm a backend actually issued
        the role or permission claim your frontend expects, or when a third-party API token isn't
        behaving as documented and you want to see its raw contents.</p>
        <p>One claim gets special treatment: if the payload includes a standard "exp" (expiry)
        field, the tool reads that Unix timestamp and tells you plainly whether the token is
        currently valid or already expired, saving you the manual timestamp math when you're
        trying to figure out why an API call is suddenly returning 401.</p>
        <p>What this tool deliberately does not do is verify the signature — that would require
        the signing secret or public key, which you should never paste into a third-party site
        regardless of how trustworthy it claims to be. Decoding tells you what a token says about
        itself; verifying tells you whether to trust it, and that step belongs in your own
        backend, with your own keys, not in a browser tool.</p>
      `.trim(),
    },
    related: ['base64-codec', 'hash-generator', 'json-formatter'],
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    category: 'developer',
    kind: 'client-pure',
    icon: 'text',
    description: 'Generate placeholder Lorem Ipsum text by paragraphs, sentences, or words.',
    component: 'LoremIpsumGenerator',
    seo: {
      title: 'Lorem Ipsum Generator — Free Placeholder Text Tool',
      description:
        'Generate classic Lorem Ipsum placeholder text by paragraphs, sentences, or word count for mockups and wireframes. Instant, no network calls.',
      keywords: ['lorem ipsum generator', 'placeholder text generator', 'dummy text generator', 'filler text'],
      faq: [
        {
          q: 'Why is Lorem Ipsum used instead of real words?',
          a: 'Because it resembles natural language\u2019s rhythm and letter/word-length distribution without being readable, viewers and designers focus on layout, typography, and spacing instead of getting distracted reading the actual content.',
        },
        {
          q: 'Can I generate an exact word count?',
          a: 'Yes, the words mode lets you specify an exact count, useful when testing how a layout handles a specific character or word budget, like a tweet-length caption or a fixed-width card.',
        },
        {
          q: 'Does the output always start with "Lorem ipsum dolor sit amet"?',
          a: 'By default yes, since that\u2019s the traditional opening recognized by anyone who works in design — though you can disable that if you specifically want fully randomized passages instead.',
        },
      ],
      content: `
        <p>Lorem Ipsum is scrambled, mostly meaningless Latin text descended from a passage in
        Cicero, and it has been the default placeholder text in publishing and design for
        decades. The reason it stuck around is specific: its letter frequency, average word
        length, and sentence rhythm closely resemble real prose, which means a page filled with it
        looks and flows like a page of real content — but because it's not actually readable
        language, nobody reviewing a layout gets distracted reading the words instead of judging
        the design.</p>
        <p>This generator produces that text in three modes depending on what you're testing.
        Paragraph mode is the most common case — mocking up a blog post, an article layout, or any
        block of body copy where you want several paragraphs of consistent placeholder content.
        Sentence mode is useful for shorter UI elements like card descriptions or pull quotes
        where a full paragraph would be too long. Word mode lets you specify an exact count, handy
        for testing how a layout handles a precise character or word budget — a notification
        snippet, a fixed-width label, a tweet-length caption.</p>
        <p>Generation is entirely deterministic from a fixed classical word list and runs
        instantly with no network call, which matters when you're iterating quickly on a design
        and don't want a placeholder-text request to be the slowest part of your workflow.</p>
        <p>Typical uses: filling in a CMS template before real copy exists so a client or
        stakeholder can review layout and spacing, stress-testing how a component handles
        long versus short content, or populating a design mockup in Figma-adjacent workflows
        where you're exporting HTML/CSS directly rather than designing visually first.</p>
      `.trim(),
    },
    related: ['regex-tester', 'json-formatter'],
  },
];
